<?php
function expresspay_card_drupal_commerce_menu() {
	//связь url и функций-обработчиков
	
	$items = array();
	$items['commerce/expresspay_card/notify'] = array(
		'title' => 'Payment notify',
		'page callback' => 'expresspay_card_drupal_commerce_notify',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
	);
	$items['commerce/expresspay_card/success'] = array(
		'title' => 'Payment success',
		'page callback' => 'expresspay_card_drupal_commerce_success',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
	);
	$items['commerce/expresspay_card/fail'] = array(
		'title' => 'Payment fail',
		'page callback' => 'expresspay_card_drupal_commerce_fail',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
	);
	return $items;
	
}

//Implements hook_commerce_payment_method_info().
function expresspay_card_drupal_commerce_commerce_payment_method_info() {
	//Базовая информация о способе оплаты,
	//нужно ли покупателю покидать пределы сайта при оплате заказа этим способом,
	//автоматический редирект на сторонний сайт при оплате заказа
	
	return array(
		'expresspay_card_drupal_commerce' => array(
			'title' => t('Банковские карты онлайн'),
			'description' => t('Оплата с помощью банковских карт VISA, MasterCard, БЕЛКАРТ, Maestro онлайн'),
			'terminal' => FALSE,
			'offsite' => TRUE,
			'offsite_autoredirect' => TRUE,
			'active' => TRUE,
		),
	);
}

//Payment method callback: settings form.
function expresspay_card_drupal_commerce_settings_form($settings = NULL) {
	//Если способ оплаты имеет настройки, то реализуем callback в этой функции
		
	$form = array();
	
	$settings = $setting == null ? (array)$settings + array(
		'url_api'				=> 'https://api.express-pay.by/v1/web_cardinvoices',
		'url_sandbox_api'		=> 'https://sandbox-api.express-pay.by/v1/web_cardinvoices',
		'handler_url'			=> $GLOBALS['base_root'].'/commerce/expresspay_card/notify',
		'db_status_wait' 		=> 'processing',
		'serviceId'				=> ''
	) : $setting;

	$form['token'] = array(
		'#type' => 'textfield',
		'#title' => t('Токен'),
		'#description' => t('Генерирутся в панели express-pay.by'),
		'#default_value' => $settings['token'],
	  );
	  $form['serviceId'] = array(
		'#type' => 'textfield',
		'#title' => t('Номер услуги'),
		'#description' => t('Номер услуги в express-pay.by'),
		'#default_value' => $settings['serviceId'],
	  );
	  $form['handler_url'] = array(
		'#type' => 'textfield',
		'#title' => t('Адрес для уведомлений'),
		'#default_value' => $settings['handler_url'],
		'#disabled' => true,
	  );
	  $form['secret_key'] = array(
		'#type' => 'textfield',
		'#title' => t('Секретное слово для подписи счетов'),
		'#description' => t('Секретного слово, которое известно только серверу и клиенту. Используется для формирования цифровой подписи. Задается в панели express-pay.by'),
		'#default_value' => $settings['secret_key'],
	  );
	  $form['secret_key_norify_mode'] = array(
		'#type' => 'checkbox',
		'#title' => t('Использовать цифровую подпись в уведомлениях.  Задается в панели express-pay.by'),
		'#default_value' => $settings['secret_key_norify_mode'],
	  );
	  $form['secret_key_norify'] = array(
		'#type' => 'textfield',
		'#title' => t('Секретное слово для подписи уведомлений'),
		'#description' => t('Секретного слово, которое известно только серверу и клиенту. Используется для формирования цифровой подписи. Задается в панели express-pay.by'),
		'#default_value' => $settings['secret_key_norify'],
	  );
	  $form['test_mode'] = array(
		'#type' => 'checkbox',
		'#title' => t('Использовать тестовый режим'),
		'#default_value' => $settings['test_mode'],
	  );
	  $form['url_api'] = array(
		'#type' => 'textfield',
		'#title' => t('Адрес API'),
		'#default_value' => $settings['url_api'],
	  );
	  $form['url_sandbox_api'] = array(
		'#type' => 'textfield',
		'#title' => t('Адрес тестового API'),
		'#default_value' => $settings['url_sandbox_api'],
	  );
	  $form['db_status_wait'] = array(
		'#type'				=> 'select',
		'#title'			=> t('Статус заказа после оплаты'),
		'#description'		=> t('Выберите статус заказа, который будет отображаться после оплаты.'),
		'#options'			=> array('processing' => 'processing', 'cart' => 'cart', 'completed' => 'completed'),
		'#default_value'	=> $settings['db_status_wait'],
	);
	$form['message_success'] = array(
		'#type' => 'textarea',
		'#title' => t('Сообщение при успешном заказе'),
		'#default_value' => $settings['message_success'],
	  );

	$form['#submit'][] = variable_set('expresspay_card_drupal_commerce_settings', $form);
	return $form;
}

//Payment method callback: submit form.
function expresspay_card_drupal_commerce_submit_form($payment_method, $pane_values, $checkout_pane, $order) {
	//Если при выборе способа оплаты нужно показывать какую-нибудь информацию
	//или для оплаты от покупателя требуются дополнительные данные,
	//то реализуем callback expresspay_card_drupal_commerce_submit_form()
	
	$build = array();
	$variables_expresspay = array(
		'path' => 'https://express-pay.by/Media/Images/Logo.png',
		'alt' => 'ExpressPay',
		'title' => 'ExpressPay',
		'attributes' => array('class' => 'logo-card'),
	);
	$text = theme('image', $variables_expresspay);
	$text .= '<div class="desc">' . t('Оплата с помощью банковских карт VISA, MasterCard, БЕЛКАРТ, Maestro онлайн') . '</div>';
	$build['print_receipt'] = array('#markup' => $text);
	return $build;
}

//Payment method callback: payment redirect form.
function expresspay_card_drupal_commerce_redirect_form($form, &$form_state, $order, $payment_method) {

	//формируем форму с данными, которые будут отправлены на сайт ExpressPay
	$wrapper = entity_metadata_wrapper('commerce_order', $order);
	//Сумма заказа:
	$amount = $wrapper->commerce_order_total->amount->value();

	$currency = $wrapper->commerce_order_total->currency_code->value();

	$currency_code = $currency == 'BYN' ? 933 : $currency;

	$amount = commerce_currency_amount_to_decimal($amount,$currency);

	$amount = str_replace('.',',',$amount);

	$order_id = $order->order_id;
	
	$test_mode = expresspay_card_drupal_commerce_get_settings('test_mode');

	$form['#action'] = $test_mode ? expresspay_card_drupal_commerce_get_settings('url_sandbox_api') : expresspay_card_drupal_commerce_get_settings('url_api');


	$service_id = expresspay_card_drupal_commerce_get_settings('serviceId');

	//drupal_set_message(t('amount : ' . $amount), 'debug');

	$form['serviceid'] 			= array('#type' => 'hidden', '#value' => $service_id);
	$form["accountno"]			= array('#type' => 'hidden', '#value' => $order_id);
	$form["amount"]				= array('#type' => 'hidden', '#value' => $amount);
	$form["currency"]			= array('#type' => 'hidden', '#value' => $currency_code);
	$form["info"]				= array('#type' => 'hidden', '#value' => 'Оплата заказа номер ' .$order_id. ' в магазине r-velo.by');
	$form["returntype"]			= array('#type' => 'hidden', '#value' => 'redirect');
	$form["returnurl"]			= array('#type' => 'hidden', '#value' => $GLOBALS['base_root'].'/commerce/expresspay_card/success?accountno=' . $order_id);//$GLOBALS['base_root'].'/commerce/expresspay_card/success';
	$form["failurl"]			= array('#type' => 'hidden', '#value' => $GLOBALS['base_root'].'/commerce/expresspay_card/fail');//$GLOBALS['base_root'].'/commerce/expresspay_card/fail';

	//формирования массива для цифровой подписи
	$sign_params = array(
		'token' 			=> expresspay_card_drupal_commerce_get_settings('token'),
		'serviceid' 		=> $service_id,
		'accountno' 		=> $order_id,
		'amount'			=> $amount,
		'currency'			=> $currency_code,
		'expiration'		=> '',
		'info'				=> 'Тест',
		'returnurl'			=> $GLOBALS['base_root'].'/commerce/expresspay_card/success',
		'failurl'			=> $GLOBALS['base_root'].'/commerce/expresspay_card/fail',
		'returntype'		=> 'redirect'
	);

	$signature = compute_signature_add_cardinvoice($sign_params,'');

	$form['signature'] = array('#type' => 'hidden', '#value' => $signature);
		
	$form['submit'] = array(
		'#type' => 'submit',
		'#value' => t('Оплатить')
	);

	$status = expresspay_card_drupal_commerce_get_settings('db_status_wait');

	db_query("UPDATE {commerce_order} SET status = 'pending' WHERE order_id = $order_id");

	return $form;
}

//Menu callback.
function expresspay_card_drupal_commerce_notify() {
	//принимает уведомление об оплате от ExpressPay
		
	try{	
		if(!empty($_POST)) {
			
			$dataJSON = ( isset($_REQUEST['Data']) ) ? htmlspecialchars_decode($_REQUEST['Data']) : '';

			$dataJSON = stripcslashes($dataJSON);

			$secret_key_norify_mode = expresspay_card_drupal_commerce_get_settings('secret_key_norify_mode');

			$secret_word = expresspay_card_drupal_commerce_get_settings('secret_key_norify');

			if($secret_key_norify_mode)
			{
				$sign = expresspay_card_drupal_commerce_computeSignature($dataJSON, $secretWord);

				$hash = ( isset($_REQUEST['Signature']) ) ? $_REQUEST['Signature'] : '';

				if(!isset($hash) || empty($hash) || $hash != $sign)
				{
					watchdog('expresspay_card_drupal_commerce', 'Wrong signature received. %sig_int != %sig_in', array(
					'%sig_int' => $hash,
					'%sig_in' => $notify_signature,
					), WATCHDOG_ERROR);
					header("HTTP/1.0 400 Bad Request");
					print("HTTP/1.0 400 Bad Request");	

					return;
				}
			}

			$data = json_decode($dataJSON, true);

			$cmdType 	= $data['CmdType'];

			if($cmdType == 3)
			{
				$status = $data['Status'];
				
				if($status == 3)
				{
					$accountNo 	= $data['AccountNo'];

					/*$order = commerce_order_load($accountNo);
					$wrapper = entity_metadata_wrapper('commerce_order', $order);
					$amount = $wrapper->commerce_order_total->amount->value();
					// Create transaction
					$transaction = commerce_payment_transaction_new('expresspay_card_drupal_commerce', $order->order_id);
					$transaction->instance_id = $order->data['payment_method'];
					$transaction->amount = $amount;
					$transaction->status = COMMERCE_PAYMENT_STATUS_SUCCESS;
					$transaction->message = t('The payment has completed.');
					commerce_payment_transaction_save($transaction);
						
					$status = expresspay_card_drupal_commerce_get_settings('db_status_wait');
					db_query("UPDATE {commerce_order} SET status = '$status' WHERE order_id = {$order->order_id}");
					*/
					expresspay_card_drupal_commerce_process_order($accountNo);

					header("HTTP/1.0 200 OK"); // генерация HTTP-заголовка
					print ("HTTP/1.0 200 OK");

				}
			} 
			else 
			{
				header("HTTP/1.0 200 OK"); // генерация HTTP-заголовка
				print ("HTTP/1.0 200 OK");
				return;
			}
		}
		else{
			header("HTTP/1.0 400 FAIL"); // генерация HTTP-заголовка
			print ("HTTP/1.0 400 FAIL");
		}
	}catch(Exception $e){
		
		watchdog(
			'expresspay_card_drupal_commerce',
			'Exception_Message: '. $e->getMessage(),
			NULL
		  );


		header("HTTP/1.0 500 FAIL"); // генерация HTTP-заголовка
		print ("HTTP/1.0 500 FAIL");
	}
}

function expresspay_card_drupal_commerce_success() {
	//оплата совершена. уведомление
	if(isset($_GET['ExpressPayAccountNumber'])) {
		$order_id = $_GET['ExpressPayAccountNumber'];
		/*$order = commerce_order_load($order_id);
		commerce_payment_redirect_pane_next_page($order);
		drupal_goto(commerce_checkout_order_uri($order));*/
		expresspay_card_drupal_commerce_process_order($order_id);
		drupal_set_message(t('Оплата прошла успешно'), 'status');
		drupal_goto('cart/');
	}
	else {
		drupal_set_message(t('Оплата прошла успешно'), 'status');
		drupal_goto('cart/');
	}
}

function expresspay_card_drupal_commerce_fail() {
	//оплата не совершена. Перенаправление в корзину
	drupal_set_message(t('Ошибка, пожалуйста, повторите попытку.'), 'error');
	drupal_goto('cart/');
}

function expresspay_card_drupal_commerce_get_settings($settings) {
	//возвращает $output со значение из форм(expresspay_card_drupal_commerce_settings_form)
		
	$output = '';
	$vars = variable_get('expresspay_card_drupal_commerce_settings', '');
	if (!empty($vars)) {
		foreach ($vars as $key=>$var) {
			if ($key == $settings) {
				$output = $vars[$key]['#default_value'];
				break;
			}
		}
	}
	return $output;
}

function compute_signature_add_cardinvoice($request_params, $secret_word) {
	$secret_word = trim($secret_word);
	$normalized_params = array_change_key_case($request_params, CASE_LOWER);
	$api_method = array(
		"token",
		"serviceid",
		"accountno",
		"expiration",
		"amount",
		"currency",
		"info",
		"returnurl",
		"failurl",
		"language",
		"sessiontimeoutsecs",
		"expirationdate",
		"returntype"
	);

	foreach ($api_method as $item)
		$result .= ( isset($normalized_params[$item]) ) ? $normalized_params[$item] : '';

	$hash = strtoupper(hash_hmac('sha1', $result, $secret_word));

	return $hash;
}

function expresspay_card_drupal_commerce_computeSignature($json, $secretWord) {
    $hash = NULL;
    
    if (empty(trim($secretWord)))
	$hash = strtoupper(hash_hmac('sha1', $json, ""));
    else
        $hash = strtoupper(hash_hmac('sha1', $json, $secretWord));
    return $hash;
}

function expresspay_card_drupal_commerce_process_order($accountNo)
{
	$order = commerce_order_load($accountNo);
	$wrapper = entity_metadata_wrapper('commerce_order', $order);
	//checkout_payment
	$amount = $wrapper->commerce_order_total->amount->value();
	// Create transaction
	$transaction = commerce_payment_transaction_new('expresspay_card_drupal_commerce', $order->order_id);
	$transaction->instance_id = $order->data['payment_method'];
	$transaction->amount = $amount;
	$transaction->status = COMMERCE_PAYMENT_STATUS_SUCCESS;
	$transaction->message = t('The payment has completed.');
	commerce_payment_transaction_save($transaction);
		
	$status = expresspay_card_drupal_commerce_get_settings('db_status_wait');
	db_query("UPDATE {commerce_order} SET status = '$status' WHERE order_id = {$order->order_id}");
}